spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/local_friends
    username: postgres
    password: annhj116!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 10000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}

#aws:
#  s3:
#    accessKey: ${AWS_ACCESS_KEY_ID}
#    secretKey: ${AWS_SECRET_ACCESS_KEY}
#    bucketName: ${AWS_S3_BUCKET_NAME}
#    region: ${AWS_REGION}

kakao:
  client:
    id: ${KAKAO_ID}
    secret: ${KAKAO_SECRET}
  redirect:
    url: ${KAKAO_REDIRECT_URL}